# .. This program simulates a finite-sized Wright-Fisher model. It computes the clone size distribution at the end of
# .. a selective sweep. Adapted from R. Gomulkiewicz http://public.wsu.edu/~gomulki/mathgen/materials/wrightfisher.R

# .. Reference:
# .. Couce, A.; Rodriguez-Rojas, A. and Blazquez J.(2016). 'Determinants of genetic diversity of spontaneous drug-resistance 
# .. in bacteria'. Genetics.

# .. parameters
s <- 0.5		# selection coefficient of the mutant type
N <-100000		# total population size
mu <- 0.00005		# mutation rate
generations <- 1000 	# expected generations (needed to allocate data)
genotypes <- 1000	# expected genotypes (needed to allocate data)

# .. variables
j=matrix(0,generations,genotypes) 	# mutant population matrix
N_i=N 					# wild-type population
clones=0
clones_i=0
i=1

while (N_i/N>0.1)	{  	# run simulation until selective sweep is almost ended (90%)
	i=i+1	
	mut=0
	mut <- rpois(1,N_i*mu) 	# mutants generated by the wildtype population
	clones <- clones + mut
	w_prom <-(sum(j[i-1,])*(1+s)+N_i*1)/(sum(j[i-1,])+N_i)  # average fitness
	print(c(i,N_i, w_prom)) 				# report progress

	for(k in 1:clones_i)	{
		f <- j[i-1,k]*(1+s)/((sum(j[i-1,])+N_i)*w_prom) # expected frequency of each genotype for next generation
		j[i,k]=rbinom(1,N,f)  				# compute actual frequency as a binomial random variable
		}
	if (mut>0) {
		for(m in 1:mut)	{
			j[i,clones_i+m]=j[i,clones_i+m]+1	# allocate mutations
			}
		}
	N_i<-N-sum(j[i,])	# update wild-type population size
	clones_i<-clones
	if (N_i<0) {N_i<-0}
	}

# .. graphical output

x11(width = 12, height = 7)
par(mfrow=c(1,2))
par(cex=1.2)
matplot(1:i,j[1:i,]/N,type="l",ylab="freq(A)",xlab="generation", log='y', ylim=c(0.000003,1),yaxt="n", xlim=c(1,30)) 

ylab=seq(-5,0,by=1)
yat=10^ylab
axis(2, at=yat, labels=yat,las=1, lwd=.5, tcl=-0.5, las=3)

ylab=seq(2,9,by=1)
for (l in seq(-6,0,1)) {
yat=ylab*10^l
axis(2, at=yat, labels=NA,las=1, lwd=.5, tcl=-0.25)
}

a<-j[i,1:500]/N
barplot((a[order(a,decreasing=TRUE)]),xlim=c(1,90),ylim=c(0,0.25),xlab="clone rank")
axis(1,c(1,15,30,45,60,75,90))
print(clones)
